### ISSUE TITLE
Feature request: Check for cyclic dependencies

### ISSUE THREAD

**Issue by marcauberer** [compose-spec/compose-go#188]
Hi,
I have a feature request for you: At the moment the loader accepts a compose file with cyclic dependencies, even when the validation step is enabled.

With cyclic dependencies, I mean something like this:
```
services:
   service1:
      depends_on:
         - service2
   service2:
      depends_on:
         - service3
   service3
      depends_on:
         - service1
```
