### ISSUE TITLE
Invalid type of Published attribute in ServicePortConfig

### ISSUE THREAD

**Issue by AhmedGrati** [compose-spec/compose-go#312]
# Description
In the `ServicePortConfig` struct, the `Published` attribute is of type string. However, such implementation led to some problems when in docker-compose. In fact, considering this docker-compose YAML file:
```yaml
version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
```
The output of the command `docker compose convert` is the following
```yaml
name: compose
services:
  nginx:
    image: nginx
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
networks:
  default:
    name: compose_default
```
As you can see, the `published` attribute is of string type, which lead to this error while executing `docker stack deploy`:
```
services.nginx.ports.0.published must be a integer
```
This issue is mainly related to an [issue raised in docker compose repository](https://github.com/docker/compose/issues/9916).
