### ISSUE TITLE
`transformMappingOrList` makes wrong assumption that `value` is of `string` type and panics when it is not.

### ISSUE THREAD

**Issue by tigerinus** [compose-spec/compose-go#394]
I have a compose yaml where `environment` is defined using array syntax according to https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment

```yaml
services:
  emby:
    image: linuxserver/emby:4.6.7
    environment:
      - host: "1000"
        container: PGID
      - host: "1000"
        container: PUID
      - host: America/Los_Angeles
        container: TZ
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
      - target: 8920
        published: "8920"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/emby/config
        target: /config
      - type: bind
        source: /DATA/Media/TV Shows
        target: /data/tvshows
      - type: bind
        source: /DATA/Media/Movies
        target: /data/movies
    devices: []
    network_mode: _default
    privileged: true
    cap_add: []
    restart: unless-stopped
    command: []
    cpu_shares: 90
    deploy:
      resources:
        reservations:
          memory: 3922
```

When loading using following code:

```go
	project, err := loader.Load(
		types.ConfigDetails{
			ConfigFiles: []types.ConfigFile{
				{
					Content: []byte(yaml),
				},
			},
			Environment: map[string]string{},
		},
        )
```

it panics at

![image](https://user-images.githubusercontent.com/7172560/235244408-a1d3f5c6-642c-424a-ad8e-f7e39fea4569.png)

full callstack when it panics:
```
2023/04/28 15:49:16 http: panic serving 127.0.0.1:58254: interface conversion: interface {} is map[string]interface {}, not string
goroutine 63 [running]:
net/http.(*conn).serve.func1()
        /home/wxh/.local/go/src/net/http/server.go:1854 +0x148
panic({0x32de6e0, 0xc00096ab40})
        /home/wxh/.local/go/src/runtime/panic.go:890 +0x262
github.com/compose-spec/compose-go/loader.transformMappingOrList({0x3134ec0, 0xc000011ad0}, {0x3b5b9e0, 0x1}, 0x1)
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:1104 +0x51e
github.com/compose-spec/compose-go/loader.transformMappingOrListFunc.func1({0x3134ec0, 0xc000011ad0})
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:1093 +0x8c
github.com/compose-spec/compose-go/loader.createTransformHook.func1({0x3134ec0, 0xc000011ad0}, {0x3b9f420, 0x33c6c80}, {0x3134ec0, 0xc000011ad0})
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:447 +0xe9
github.com/mitchellh/mapstructure.DecodeHookExec({0x33071c0, 0xc000cbd960}, {0x3134ec0, 0xc000011ad0, 0x97}, {0x33c6c80, 0xc000cc66e0, 0x195})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:47 +0x4f2
github.com/mitchellh/mapstructure.ComposeDecodeHookFunc.func1({0x3134ec0, 0xc000011ad0, 0x97}, {0x33c6c80, 0xc000cc66e0, 0x195})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:69 +0x1c5
github.com/mitchellh/mapstructure.DecodeHookExec({0x3276620, 0xc0008949a0}, {0x3134ec0, 0xc000011ad0, 0x97}, {0x33c6c80, 0xc000cc66e0, 0x195})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:51 +0x305
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc0000132a0, {0x3147430, 0xb}, {0x3134ec0, 0xc000011ad0}, {0x33c6c80, 0xc000cc66e0, 0x195})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:459 +0x1e8
github.com/mitchellh/mapstructure.(*Decoder).decodeStructFromMap(0xc0000132a0, {0x0, 0x0}, {0x328c100, 0xc00096a030, 0x15}, {0x36477a0, 0xc000cc6500, 0x199})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1411 +0x1cca
github.com/mitchellh/mapstructure.(*Decoder).decodeStruct(0xc0000132a0, {0x0, 0x0}, {0x328c100, 0xc00096a030}, {0x36477a0, 0xc000cc6500, 0x199})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1235 +0x209
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc0000132a0, {0x0, 0x0}, {0x328c100, 0xc00096a030}, {0x36477a0, 0xc000cc6500, 0x199})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:482 +0x994
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc0000132a0, {0x328c100, 0xc00096a030})
        /home/wxh/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:417 +0xc6
github.com/compose-spec/compose-go/loader.Transform({0x328c100, 0xc00096a030}, {0x3318e00, 0xc000cc6500}, {0x0, 0x0, 0x0})
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:398 +0x34b
github.com/compose-spec/compose-go/loader.LoadService({0xc000923dc8, 0x4}, 0xc00096a030, {0x0, 0x0}, 0xc0010afa68, 0x0, 0x0)
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:616 +0x105
github.com/compose-spec/compose-go/loader.loadServiceWithExtends({0x0, 0x0}, {0xc000923dc8, 0x4}, 0xc000953fb0, {0x0, 0x0}, 0xc0010afa68, 0xc0001e2ff0, 0xc0010af2f8)
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:538 +0x279
github.com/compose-spec/compose-go/loader.LoadServices({0x0, 0x0}, 0xc000953fb0, {0x0, 0x0}, 0xc0010afa68, 0xc0001e2ff0)
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:513 +0x2c5
github.com/compose-spec/compose-go/loader.loadSections({0x0, 0x0}, 0xc000953e00, {{0x0, 0x0}, {0x0, 0x0}, {0xc0009470e0, 0x1, 0x1}, ...}, ...)
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:337 +0x43e
github.com/compose-spec/compose-go/loader.Load({{0x0, 0x0}, {0x0, 0x0}, {0xc0009470e0, 0x1, 0x1}, 0xc000947110}, {0xc000a9c530, 0x1, ...})
        /home/wxh/go/pkg/mod/github.com/compose-spec/compose-go@v1.9.0/loader/loader.go:203 +0x9aa```
