### ISSUE TITLE
Nested interpolation does not allow mixing of strings and variables, unless it ends with a variable

### ISSUE THREAD

**Issue by chrkr** [compose-spec/compose-go#401]
I was trying to use the following nested interpolation, in order to be able to override a compose-managed volume with an external one by using environment variables, while more or less keeping the default naming behaviour based on project name:

```
volumes:
  pgdata:
    name: ${DB_VOLUME_NAME:-${COMPOSE_PROJECT_NAME}_pgdata}
    external: ${DB_VOLUME_EXTERNAL:-false}
```

This results in an error:
```
invalid interpolation format for volumes.pgdata.name.
You may need to escape any $ with another $.
${COMPOSE_PROJECT_NAME
```

However, the following works and gives the expected results:
```
volumes:
  pgdata:
    name: ${DB_VOLUME_NAME:-${COMPOSE_PROJECT_NAME}_pgdata${X:-}}
    external: ${DB_VOLUME_EXTERNAL:-false}
```

Here `X` is not set, which causes that part to default to an empty string, and this does give the intended result of the volume being named `<project name>_pgdata` if `DB_VOLUME_NAME` has not been set:

```
$ docker compose config | yq .volumes
pgdata:
  name: myproject_pgdata
```

All of the following work:
```
x-names:
  a: ${DB_VOLUME_NAME:-${COMPOSE_PROJECT_NAME}_pgdata${A:-}}
  b: ${DB_VOLUME_NAME:-${COMPOSE_PROJECT_NAME}${A:-_pgdata}}
  c: ${DB_VOLUME_NAME:-pgdata_${COMPOSE_PROJECT_NAME}}
  d: ${DB_VOLUME_NAME:-${A:-a}_pgdata_${B:-a}_c_${COMPOSE_PROJECT_NAME}}
  e: ${DB_VOLUME_NAME:-${A:-a}_pgdata_${B:-${C:-}_${D:-d}}_c_${COMPOSE_PROJECT_NAME}}
```

Result:
```
$ docker compose config | yq .x-names
a: myproject_pgdata
b: myproject_pgdata
c: pgdata_myproject
d: a_pgdata_a_c_myproject
e: a_pgdata__d_c_myproject
```

Clearly compose is absolutely fine with any mix of strings and variables, _so long as the last one is a variable and not a string_.
