### ISSUE TITLE
Service extensions do not following specification, needs clarification or correction

### ISSUE THREAD

**Issue by lod** [compose-spec/compose-go#450]
The specification states that x-extension fields, "They can be used within any structure in a Compose file as Compose ignores any fields that start with x-."

https://github.com/compose-spec/compose-spec/blob/327dade9e53e386856fcae70a488c27a46397058/11-extension.md

#91 raised that the x-kiosk service not starting, informed that this was expected behaviour and changes were made upstream. (ticket not closed though)

#413 explicitly adds support for services such as x-kiosk as services, and breaks support for extensions at the service level.  This violates the compose-spec.

Given the following structure.

```yaml
services:
  x-abstract: &abstract
    image: ubuntu
    network_mode: host

  concrete:
    <<: *abstract
    command: do_something
```

The compose specification says that we should get one container, concrete.  Compose should ignore x-abstract.

Current actual behaviour (docker compose v2.20.3) is that we get two containers, x-abstract and concrete.
