### ISSUE TITLE
Target ports cannot be set to range when using long syntax

### ISSUE THREAD

**Issue by Neirda24** [compose-spec/compose-go#504]
Converting

```yaml
services:
    my-service:
        ports:
            - '20-21:20-21/tcp'
            - '40000-40009:40000-40009/tcp'
```

to 

```yaml
services:
    my-service:
        ports:
            -
                target: '20-21'
                published: '20-21'
                protocol: 'tcp'
            -
                target: '40000-40009'
                published: '40000-40009'
                protocol: 'tcp'
```

fails with :

`services.my-service.ports.[].target`: failed to cast to expected type: strconv.Atoi: parsing "20-21": invalid syntax

---

It seems `published` correctly supports ranges but `target` doesn't
