### ISSUE TITLE
Validation doesn't catch multiple services with the same container_name

### ISSUE THREAD

**Issue by maxsokolovsky** [compose-spec/compose-go#583]
The following configuration declares two services, each of which has the `container_name` specifies.
But those container names are the same.

```yaml
version: '3.4'
services:
  webservice1:
    container_name: foo
    image: nginx
  webservice2:
    container_name: foo
    image: nginx
```

I can run `docker compose up` with the following configuration.
But there will be an error at runtime from Docker,
so one of the two containers will not start.

Why doesn't compose validate this and issue an error before running any containers?

**Comment by maxsokolovsky** [comment]
Thank you so much for the fast response! One question: would this fix make it to the v1 line of releases? Will there be any v1 further releases at all?

**Comment by shippo16** [comment]
Hi there.

Please consider our use case. `docker-compose.yml`:

```YAML
services:

nginx-unit-device-server: &default-device-server
  container_name: api-server
  image: api-nginx-unit-server:1.8
  healthcheck:
    test: python3 /usr/src/app/container_healthcheck.py
    interval: 30s
    timeout: 5s
    retries: 5
    start_period: 30s
  . . .
   
uwsgi-device-server:
  <<: *default-device-server
  image: api-uwsgi-server:1.8

gunicorn-device-server:
  <<: *default-device-server
  image: api-gunicorn-server:1.8

socket-server: &default-socket-server
  . . .

device-controllers: &default-device-controllers
  container_name: device-controllers
  image: controllers:1.9
  depends_on:
    gunicorn-device-server:
      condition: service_healthy
    socket-server:
      condition: service_healthy
  . . .
```
So `docker compose up device-controllers` would spin up
the required Compose services.

As you're aware containerised apps address services in
other containers by container name. Our containerised
controller app makes requests to the API server by
container name. The controller does not (and shouldn't)
care of what Compose service nor what Docker image is
driving this API server.

Now, starting containers with same names should throw an
error at runtime as it does. But is this not enough? What
is the issue with simply defining the services with same
names?

With this validation you're taking the logic flexibility out
of the `docker-compose.yml` file, and breaking our software.
Even though spinning up of conflicting containers would never
be attempted.
