### ISSUE TITLE
Selinux key in verbose bind mount not recognized despite being in schema

### ISSUE THREAD

**Issue by charliemirabile** [compose-spec/compose-go#615]
Hello, I was switching from the terse syntax for mounts to the verbose one in my compose files to make them easier to understand and better for tracking in version control, and I ran into a hitch with selinux support. Consider this compose file `/tmp/compose.yml`
```yaml
services:
  foo:
    image: scratch
    volumes:
      - type: bind
        source: .
        target: /mnt
        selinux: z
```
when I run docker-compose build it prints the following error:
```
$ docker-compose build
validating /tmp/compose.yml: services.foo.volumes.0 Additional property selinux is not allowed
```
This is confusing because I am using the latest version of docker compose
```
$ docker-compose --version
Docker Compose version v2.26.1
```
And as far as I can tell, docker compose is using the latest release (2.0.2) of this repository in the commit that is associated with that tag:
https://github.com/docker/compose/blob/ff20b641c7f1cce588faea476fbd1a6fdd953b36/go.mod#L10-L10

And the version of the json schema in that tag includes this entry for selinux within a bind mount:
https://github.com/compose-spec/compose-go/blob/d0722c0e5564b4970f6634592638c0577ef8e028/schema/compose-spec.json#L381-L387

Perhaps there is an issue with the compose-spec.json?

**Comment by glours** [comment]
Hey @charliemirabile 
As describe in `the compose-spec.json` and in the [Compose specification](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#long-syntax-5), `bind` could be the type of the volume but also an attribute to add more details about the mount option, so the correct syntax to declare `selinux` option is :
```yaml
services:
  foo:
    image: scratch
    volumes:
      - type: bind
        source: .
        target: /mnt
        bind:
          selinux: z
```
