### ISSUE TITLE
Resource cpus value has wrong type when calling MarshalYAML export

### ISSUE THREAD

**Issue by donknap** [compose-spec/compose-go#712]
Original Yaml :

```
services:
  nginx_proxy:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: 4.00
          memory: 500M
```

code: 

```
// make 
overrideYaml, err := compose.Project.MarshalYAML()
if err != nil {
return nil, err
}
```

error:

![图片](https://github.com/user-attachments/assets/b188bb74-67f5-4ce9-9e1a-e57929da54e4)
